# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_name', models.CharField(max_length=100)),
                ('publisher_name', models.CharField(max_length=100)),
                ('impression', models.PositiveIntegerField(default=0)),
                ('click', models.PositiveIntegerField(default=0)),
                ('install', models.PositiveIntegerField(default=0)),
                ('purchase', models.PositiveIntegerField(default=0)),
                ('os', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('device_brand', models.CharField(max_length=100)),
            ],
        ),
    ]
